# Generated by Django 4.1.5 on 2023-01-17 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_event', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('poster', models.ImageField(upload_to='poster/%Y')),
                ('tech_info', models.FileField(blank=True, null=True, upload_to='tech_files/%Y')),
                ('result', models.URLField(blank=True, db_index=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('registration_deadline', models.DateTimeField(null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(choices=[('м21А', 'М21А'), ('м21Е', 'М21Е'), ('ж21А', 'Ж21А'), ('ж21Е', 'Ж21Е')], max_length=4)),
                ('data_reg', models.DateField(blank=True, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.events')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
