# Generated by Django 4.1.4 on 2023-01-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_app', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='note_images', verbose_name='Image'),
        ),
    ]
