# Generated by Django 4.1.4 on 2023-01-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_app', '0004_note_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='note_images/', verbose_name='Image'),
        ),
    ]
