# Generated by Django 4.1.4 on 2023-01-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_app', '0005_alter_note_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='note_name',
            field=models.TextField(default='note name'),
            preserve_default=False,
        ),
    ]
