# Generated by Django 4.1.4 on 2023-01-11 03:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebook_app', '0006_multipleimage_note_note_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('topic_name', 'owner')},
        ),
    ]
