# Generated by Django 4.1.4 on 2023-01-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_app', '0007_alter_topic_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('note_name', 'topic')},
        ),
    ]
