# Generated by Django 4.1.4 on 2023-01-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_app', '0008_alter_note_text_alter_note_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_name',
            field=models.CharField(max_length=200),
        ),
    ]
