# Generated by Django 4.1.4 on 2023-01-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_app', '0010_alter_note_note_name_alter_topic_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=200),
        ),
    ]
