# Generated by Django 4.1.3 on 2022-12-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworking',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='coworking',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='coworking',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coworking',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='coworking',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='coworking',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
