# Generated by Django 4.1.3 on 2022-12-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0002_alter_coworking_content_alter_coworking_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworking',
            name='photo',
            field=models.ImageField(upload_to='coworking/img/', verbose_name='Фото'),
        ),
    ]
