# Generated by Django 4.1.3 on 2022-12-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0003_alter_coworking_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworking',
            name='photo',
            field=models.ImageField(upload_to='coworking/static/coworking/img/', verbose_name='Фото'),
        ),
    ]
