# Generated by Django 4.1.3 on 2022-12-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0005_alter_coworking_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coworking',
            options={'ordering': ['title', 'time_update'], 'verbose_name': 'Коворкинги', 'verbose_name_plural': 'Коворкинги'},
        ),
        migrations.AlterField(
            model_name='coworking',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='coworking',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
