# Generated by Django 4.1.3 on 2022-12-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0007_cities_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='connect',
        ),
        migrations.AddField(
            model_name='location',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coworking.cities'),
        ),
    ]
