# Generated by Django 4.1.3 on 2022-12-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0009_alter_location_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Города', 'verbose_name_plural': 'Города'},
        ),
        migrations.RemoveField(
            model_name='cities',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='time_update',
        ),
        migrations.RemoveField(
            model_name='location',
            name='photo',
        ),
    ]
