# Generated by Django 4.1.3 on 2022-12-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0012_delete_categoriesheader_delete_categoriesleft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='time_create',
        ),
        migrations.AddField(
            model_name='cities',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='cities',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='cities',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='location',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
    ]
