# Generated by Django 4.1.3 on 2022-12-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0014_alter_cities_options_alter_location_cat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBelarus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('content', models.TextField(blank=True, unique=True, verbose_name='Контент')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'О Беларуси',
                'verbose_name_plural': 'О беларуси',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='addpage',
            name='content',
            field=models.TextField(blank=True, unique=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='addpage',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название Коворкинга'),
        ),
    ]
