# Generated by Django 4.1.3 on 2022-12-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0015_aboutbelarus_alter_addpage_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutbelarus',
            options={'verbose_name': 'О Беларуси', 'verbose_name_plural': 'О Беларуси'},
        ),
        migrations.AddField(
            model_name='aboutbelarus',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
    ]
