# Generated by Django 4.1.3 on 2022-12-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0016_alter_aboutbelarus_options_aboutbelarus_time_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutbelarus',
            options={'ordering': ['time_update'], 'verbose_name': 'О Беларуси', 'verbose_name_plural': 'О Беларуси'},
        ),
        migrations.RemoveField(
            model_name='addpage',
            name='num',
        ),
        migrations.AddField(
            model_name='addpage',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='Номер улицы'),
        ),
        migrations.AlterField(
            model_name='addpage',
            name='number',
            field=models.CharField(max_length=255, verbose_name='Email'),
        ),
    ]
