# Generated by Django 4.1.3 on 2022-12-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0018_newpage_delete_addpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newpage',
        ),
    ]
