# Generated by Django 4.1.3 on 2022-12-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0020_addpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpage',
            name='number',
        ),
        migrations.AddField(
            model_name='addpage',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='Email'),
        ),
    ]
