# Generated by Django 4.1.5 on 2023-01-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=100)),
                ('issued', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('sub_type', models.CharField(choices=[('0', 'new to crypto'), ('1', 'already in crypto')], max_length=1)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
