# Generated by Django 4.1.5 on 2023-01-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PopupForm',
            new_name='Orders',
        ),
    ]
