# Generated by Django 4.1.5 on 2023-01-10 14:23

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
