# Generated by Django 4.1.5 on 2023-01-14 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kid_name', models.CharField(max_length=100)),
                ('issued', models.DateTimeField()),
                ('clss_choise', models.CharField(choices=[('1', ' 1 класс'), ('2', ' 2 класс'), ('3', ' 3 класс'), ('4', ' 4 класс'), ('5', ' 5 класс'), ('6', ' 6 класс'), ('7', ' 7 класс'), ('8', ' 8 класс'), ('9', ' 9 класс'), ('10', ' 10 класс')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+123456789'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
