# Generated by Django 4.1.5 on 2023-01-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_content_mymodel_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='class_choice',
            field=models.CharField(choices=[('U', ' Unity game development class'), ('W', ' Web development class'), ('P', ' Python programming class'), ('S', ' select class')], default='S', max_length=4),
        ),
    ]
