# Generated by Django 4.1.5 on 2023-01-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_mymodel_class_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='class_choice',
            field=models.CharField(choices=[('U', ' Unity game development class'), ('W', ' Web development class'), ('P', ' Python programming class')], default='U', max_length=1),
        ),
    ]
