# Generated by Django 4.1.5 on 2023-01-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['id'], 'verbose_name': 'Автомобили VW лучшие', 'verbose_name_plural': 'Автомобили VW самые лучшие'},
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
