# Generated by Django 3.2.16 on 2023-01-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('article', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit_price_BYN', models.FloatField()),
                ('unit_price_USD', models.FloatField()),
                ('purchase_date', models.DateTimeField()),
                ('purchase_place', models.CharField(max_length=255)),
                ('update_timestamp', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('article', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('trade_mark', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('effects', models.TextField(blank=True)),
                ('nominal_amount', models.FloatField()),
                ('real_amount', models.FloatField()),
                ('measure_units', models.CharField(max_length=100)),
                ('unit_price_BYN', models.FloatField()),
                ('unit_price_USD', models.FloatField()),
                ('purchase_date', models.DateTimeField()),
                ('purchase_place', models.CharField(max_length=255)),
                ('update_timestamp', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('for_whom', models.CharField(choices=[('s', 'sell'), ('g', 'gift'), ('m', 'myself')], max_length=1)),
                ('used_materials', models.TextField()),
                ('price_BYN', models.FloatField()),
                ('price_USD', models.FloatField()),
                ('materials_price_BYN', models.FloatField()),
                ('materials_price_USD', models.FloatField()),
                ('photo', models.ImageField(upload_to='uploads')),
                ('sell_date', models.DateTimeField()),
                ('to_whom_was_given', models.JSONField(blank=True)),
                ('update_timestamp', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('article', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('trade_mark', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('effects', models.TextField(blank=True)),
                ('rest_amount', models.FloatField()),
                ('measure_units', models.CharField(max_length=100)),
                ('total_price_BYN', models.FloatField()),
                ('total_price_USD', models.FloatField()),
                ('update_timestamp', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
