# Generated by Django 3.2.16 on 2023-01-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='DefaultName', max_length=255),
            preserve_default=False,
        ),
    ]
