# Generated by Django 3.2.16 on 2023-01-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmade', '0002_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='series',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='trade_mark',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
