# Generated by Django 3.2.16 on 2023-01-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmade', '0003_auto_20230113_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sell_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='to_whom_was_given',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
