# Generated by Django 3.2.16 on 2023-01-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmade', '0004_auto_20230114_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sell_date',
            field=models.DateTimeField(),
        ),
    ]
