# Generated by Django 3.2.16 on 2023-01-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmade', '0005_alter_product_sell_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='unit_price_BYN',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='measure_units',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='real_amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_price_BYN',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials_price_BYN',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_BYN',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='used_materials',
            field=models.TextField(blank=True),
        ),
    ]
