# Generated by Django 3.2.16 on 2023-01-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmade', '0007_auto_20230114_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='article',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
